# -*- coding: utf-8 -*-
"""Arima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BGnvHy0LHbgqIe2c2oNOxrPS2vMOYHy8
"""

# Commented out IPython magic to ensure Python compatibility.
#pip install mplfinance
#pip install chart_studio
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import dates
import mplfinance as mpf
# %matplotlib inline
import statsmodels.api as sm
import seaborn as sns

import chart_studio.plotly as py
import plotly.express as px
import plotly.graph_objects as go

import cufflinks as cf # Connects Plotly to Pandas
# Makes Plotly work in your Notebook
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
cf.go_offline()

import requests # Get URL data
from bs4 import BeautifulSoup # Manipulate URL data
import json
from pandas import DataFrame as df
from statsmodels.tsa.ar_model import AutoReg, ar_select_order
from statsmodels.tsa.api import acf, pacf, graphics

df = pd.read_csv('sample_data/gas.csv', parse_dates=True)
df = df.fillna(method='ffill')
df.isnull().values.any()
sns.set_style('darkgrid')
pd.plotting.register_matplotlib_converters()
sns.mpl.rc('figure', figsize=(12,6))
fig, ax= plt.subplots()
#ax = df.plot(ax=ax)

model = AutoReg(df['Gas'], 36)
model_fit = model.fit()

train_df = df.iloc[:212]
test_df = df.iloc[212:]

train_model = AutoReg(train_df['Gas'], 72).fit(cov_type = 'HC0')

start=len(train_df)
end=len(train_df) + len(test_df) - 1

prediction = train_model.predict(start=start, end=end, dynamic=True)
ax = test_df.plot(ax=ax)
ax = prediction.plot(ax=ax)
print(prediction)

